### ISSUE TITLE
BRADING / Logo and color palette

### ISSUE THREAD

**Issue by alexeses** [jkutkutOrg/EatUp#17]
Hello team @mariaduva @Jkutkut !

Throughout this time, I have been working on improving the application's graphic design and creating some interfaces with its logic while considering the perfect combination of colors/logo for the application. Here are my proposals:

These have been some of the selected logos, with the logo being the most important aspect since all text is optional.

| Style 1 | Style 2 | Style 3 | Style 4 | Style 5 |
| --- | --- | --- | --- | --- |
| ![1](https://user-images.githubusercontent.com/46347629/230778948-e2d8974b-7e21-444a-90dd-4b2c9b4227ba.png) | ![2](https://user-images.githubusercontent.com/46347629/230778949-7d810023-bfe0-4cb6-8143-d109db126006.png) | ![3](https://user-images.githubusercontent.com/46347629/230778950-ddad3e7d-0679-40c4-b6b4-15d81de39608.png) | ![4](https://user-images.githubusercontent.com/46347629/230778951-b6598abd-9587-4b53-b001-44c5dad5791c.png) | ![5](https://user-images.githubusercontent.com/46347629/230778952-5fb1494c-750b-46ba-9d96-75e6b4281ec3.png) |

And this has been the selected color palette:
| Color | Hex code |
|-------|--------|
| ![image](https://user-images.githubusercontent.com/46347629/230779014-6afa493a-d4f7-4a72-95e2-20f28f38f2f9.png) | `#FE554A` |
| ![image](https://user-images.githubusercontent.com/46347629/230779020-38fd1705-d4d9-4823-a40b-591a6f4a6243.png) | `#F9881F` -  `#FF774C` |
| ![image](https://user-images.githubusercontent.com/46347629/230779027-7d94b7de-15e6-401a-9d5f-119bf5d1e495.png) | `#0B735F` |
| ![image](https://user-images.githubusercontent.com/46347629/230779034-83d7b8ac-f7f5-44b8-94b1-632e37aff808.png) | `#2A3037` |
| ![image](https://user-images.githubusercontent.com/46347629/230779039-4c088478-b27c-4a9b-8f91-7b718160769b.png) | `#C6C9CC` |
| ![image](https://user-images.githubusercontent.com/46347629/230779044-1455a012-eb53-4fef-8384-6833c6cf10e9.png) | `#DFE2E5` |
| ![image](https://user-images.githubusercontent.com/46347629/230779055-370e7696-9c36-4fc4-87cf-a45fd2844341.png) | `#FCFCFC` -  `#F7F7FB` |

Any suggestions, please do not hesitate to leave them in the thread. In case everyone agrees, I will work on uploading all the documented files to the project's wiki so that we can have a much simpler reference to them.

Thank you very much!

**Comment by Jkutkut** [comment]
Love it! Great work!

**Comment by alexeses** [comment]
Finish!
