### ISSUE TITLE
Staff perspective

### ISSUE THREAD

**Issue by Jkutkut** [jkutkutOrg/EatUp#2]

**Comment by mariaduva** [comment]
Hi everyone! 

Here are my ideas for the staff's experience. To make things simpler and organized, I've divided them into modules so we can discuss each one separately and in more detail.

### **MODULE 1: STAFF AUTHENTICATION**
The staff authentication window will be a secure login screen that requires staff to enter their id and password. The system will authenticate the user's credentials and provide access to the administration area if they are correct. If a new staff member needs to be added, the administrator will create a new profile for them, which will include:

- Unique login ID
- Name,
- Role
- Contact information

### **MODULE 2: ORDER MANAGEMENT**
This module will include a user-friendly interface for managing orders within the kitchen. Each order will have a unique ID, which will be used to track its progress and ensure accuracy. When an order is received, its initial status will be "in preparation". The system will display the order details, including:

- Id order
- Time of the order
- Table number
- Products ordered
- Respective quantities of each product
- Order´s status ("in preparation", "prepared")

The average preparation time for each product will be stored in the system, allowing staff to estimate when each order will be ready. Once all products in the order are ready, the status will change to "prepared" and the order can be delivered to the customer. The system will also allow staff to view a summary of all orders currently in progress, including their status, estimated time of completion, and any special requests.

### **MODULE 3: TABLE MANAGEMENT**
This module will focus on managing the tables in the restaurant, including their status and availability. A visual map of the restaurant's layout will be displayed, with icons representing each table. We will need the number of the tables and the disposition of each one on the restaurant. Clicking on a table icon will bring up a window with information about the table's orders, such as the products ordered, the status of the orders, and any special requests.

The system will allow staff to view the status of multiple tables at once, perhaps in a table or grid format that summarizes the status of each table. **TODO**: Look in depth how to use Canvas in Android [https://developer.android.com/.../Canvas](https://developer.android.com/reference/android/graphics/Canvas). This will enable staff to quickly see which tables need attention and to keep track of table availability.

### **MODULE 4: TAKE-AWAYS**
Thoughts ??? If we have time, I think it will be a great addition to the web version jeje.

I'm working on a sketch of the interfaces. When I have something more solid, I will upload it :)

**Comment by Jkutkut** [comment]
Added to wiki
