### ISSUE TITLE
Establish Git branch naming conventions 

### ISSUE THREAD

**Issue by alexeses** [jkutkutOrg/EatUp#9]
We should all agree a convention for naming our branches. My proposal would be the following:

1. **Branch type first**, followed by a hyphen (-):
   - `wip` Work in progress branches
   - `dev` Our own branches (the ones where we could merge small changes without affecting the others)
   - `rel` Release branch, the one where everything should work

2. **Feature identifier** (snake_case): What will this branch bring to the project

An example of this would be the following branch:
`wip-my_buggy_feature`

After closing this issue, the final convention should be merged on the project wiki.

Any ideas or suggestions are appreciated! ([src](https://github.com/jkutkutOrg/Android-CineHub/issues/9))

**Comment by Jkutkut** [comment]
Added to the wiki
